
import { BreadCrumbsDataProps, MetaDataProps } from "@/app/types";
import PageHeading from "@/app/ui/PageHeading";
import TopBar from "../ui/Header/TopBar";
import Footer from "../ui/Footer/Footer";
import Header from "../ui/Header/Header";

const BreadcrumbsData: BreadCrumbsDataProps = {
    backgroundImage: "https://gwd-website.b-cdn.net/lightning/bench-is-garden-there-is-bright-.png",
    title: "Terms and Conditions",
    breadcrumbs: [
        { label: "Home", link: "/", active: false },
        { label: "Terms and Conditions", link: "Terms and Conditions", active: true },
    ],
};

export const metadata: MetaDataProps = {
    title: "Terms and Conditions | Lightning Tree Service LLC",
};

export default function TermsAndCondition() {
    return (
        <>
        <TopBar />
        <Header />
            <PageHeading data={BreadcrumbsData} />
            <div className="cs_height_70 cs_height_lg_50" />
            <div className="container">
                <p className="last-updated">
                    Last Updated: {new Date().toDateString().slice(3)}
                </p>
                <p>
                    By requesting services from <strong>Lightning Tree Service LLC</strong>, you agree to the following terms and conditions regarding tree care, removals, and property access.
                </p>
                <div className="cs_text_block_wrapper">
                    <div className="cs_text_block">
                        <h2 className="cs_fs_32">1. Estimates and Quotes</h2>
                        <p>All estimates provided are valid for 30 days. We provide:</p>
                        <ul className="cs_mp_0">
                            <li>Free on-site evaluations for most residential areas.</li>
                            <li>Detailed descriptions of the work to be performed.</li>
                            <li>Clear pricing with no hidden fees unless work scope changes.</li>
                        </ul>
                    </div>

                    <div className="cs_text_block">
                        <h2 className="cs_fs_32">2. Safety and Property Access</h2>
                        <p>To ensure a safe work environment, the client agrees to:</p>
                        <ul className="cs_mp_0">
                            <li>Provide clear access to the trees and work area.</li>
                            <li>Keep children, pets, and unauthorized persons away from the work zone.</li>
                            <li>Identify any underground utilities or private irrigation systems not marked by public services.</li>
                        </ul>
                    </div>

                    <div className="cs_text_block">
                        <h2 className="cs_fs_32">3. Scheduling and Cancellations</h2>
                        <p>Tree work is weather-dependent. We reserve the right to reschedule if conditions (high winds, heavy rain) pose a safety risk. Cancellations by the client must be made at least 48 hours before the scheduled service.</p>
                    </div>

                    <div className="cs_text_block">
                        <h2 className="cs_fs_32">4. Liability and Insurance</h2>
                        <p>Lightning Tree Service LLC is fully licensed, certified, and bonded. We are not liable for:</p>
                        <ul className="cs_mp_0">
                            <li>Unforeseen damage to unmarked underground lines or structures.</li>
                            <li>Minor lawn indentations or disturbances caused by heavy equipment.</li>
                            <li>Pre-existing structural issues of trees that were not visible during the estimate.</li>
                        </ul>
                    </div>

                    <div className="cs_text_block">
                        <h2 className="cs_fs_32">5. Clean-Up and Debris</h2>
                        <p>Our standard service includes:</p>
                        <ul className="cs_mp_0">
                            <li>Removal of all brush and wood generated by our work.</li>
                            <li>Raking of the immediate work area.</li>
                            <li>Optional stump grinding (must be specified in the quote).</li>
                        </ul>
                    </div>

                    <div className="cs_text_block">
                        <h2 className="cs_fs_32">6. Governing Law</h2>
                        <p>
                            These terms shall be governed by the laws of the State of Washington, 
                            without regard to its conflict of law provisions.
                        </p>
                    </div>
                </div>
            </div>
            <div className="cs_height_70 cs_height_lg_50" />
            <Footer />
        </>
    );
}

